# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YJExtensionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YJExtensionDemo

  target 'YJExtensionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJExtensionDemoUITests' do
    # Pods for testing
  end

pod 'YJExtension', :path => '../'

end
